/*
 * Pineapple Quick Start — Pine-Java Engine Usage Example
 * ======================================================
 *
 * Pineapple is a DAG-based pipeline engine that executes operator graphs compiled
 * from the Apple DSL (Python) and runs on Go or JVM runtimes.
 *
 * Maven coordinates (once published):
 *
 *   <dependency>
 *     <groupId>page.liam</groupId>
 *     <artifactId>pine-java</artifactId>
 *     <version>0.6.6</version>
 *   </dependency>
 *
 * This example demonstrates the end-to-end workflow:
 *   1. Define a pipeline config (normally generated by Apple DSL, here hardcoded)
 *   2. Create an Engine from the JSON config
 *   3. Execute the pipeline with input data
 *   4. Inspect the result (common fields + items)
 *   5. Render the DAG for visualization
 *   6. (Commented) Run PineServer for HTTP-based execution
 */
package page.liam.pine.examples;

import page.liam.pine.Engine;
import page.liam.pine.OpTrace;
import page.liam.pine.PineServer;

import java.nio.charset.StandardCharsets;
import java.util.*;

public class QuickStart {

    // -------------------------------------------------------------------------
    // Pipeline JSON config — typically generated by Apple DSL (Python), e.g.:
    //
    //   from apple import Flow
    //   flow = Flow("content_feed")
    //   flow.recall_static("fetch_items", items=[...])
    //   flow.transform_copy("enrich", mapping={"display_score": "score"})
    //   flow.reorder_sort("rank", order="desc")
    //   flow.filter_truncate("top_k", top_n=3)
    //   flow.compile("output/content_feed.json")
    //
    // For this example, we inline a minimal config directly.
    // -------------------------------------------------------------------------
    private static final String PIPELINE_CONFIG = "{\n"
            + "  \"_PINEAPPLE_VERSION\": \"0.10.9\",\n"
            + "  \"pipeline_config\": {\n"
            + "    \"operators\": {\n"
            + "      \"fetch_items\": {\n"
            + "        \"type_name\": \"recall_static\",\n"
            + "        \"recall\": true,\n"
            + "        \"items\": [\n"
            + "          {\"item_id\": \"article_1\", \"score\": 0.92, \"category\": \"tech\"},\n"
            + "          {\"item_id\": \"article_2\", \"score\": 0.85, \"category\": \"science\"},\n"
            + "          {\"item_id\": \"article_3\", \"score\": 0.78, \"category\": \"tech\"},\n"
            + "          {\"item_id\": \"article_4\", \"score\": 0.95, \"category\": \"health\"},\n"
            + "          {\"item_id\": \"article_5\", \"score\": 0.60, \"category\": \"sports\"}\n"
            + "        ],\n"
            + "        \"$metadata\": {\n"
            + "          \"common_input\": [],\n"
            + "          \"common_output\": [],\n"
            + "          \"item_input\": [],\n"
            + "          \"item_output\": [\"item_id\", \"score\", \"category\"]\n"
            + "        }\n"
            + "      },\n"
            + "      \"enrich\": {\n"
            + "        \"type_name\": \"transform_copy\",\n"
            + "        \"mapping\": {\"display_score\": \"score\"},\n"
            + "        \"$metadata\": {\n"
            + "          \"common_input\": [],\n"
            + "          \"common_output\": [],\n"
            + "          \"item_input\": [\"score\"],\n"
            + "          \"item_output\": [\"display_score\"]\n"
            + "        }\n"
            + "      },\n"
            + "      \"rank\": {\n"
            + "        \"type_name\": \"reorder_sort\",\n"
            + "        \"order\": \"desc\",\n"
            + "        \"$metadata\": {\n"
            + "          \"common_input\": [],\n"
            + "          \"common_output\": [],\n"
            + "          \"item_input\": [\"score\"],\n"
            + "          \"item_output\": []\n"
            + "        }\n"
            + "      },\n"
            + "      \"top_k\": {\n"
            + "        \"type_name\": \"filter_truncate\",\n"
            + "        \"top_n\": 3,\n"
            + "        \"$metadata\": {\n"
            + "          \"common_input\": [],\n"
            + "          \"common_output\": [],\n"
            + "          \"item_input\": [],\n"
            + "          \"item_output\": []\n"
            + "        }\n"
            + "      }\n"
            + "    },\n"
            + "    \"pipeline_map\": {\n"
            + "      \"main_pipeline\": {\n"
            + "        \"pipeline\": [\"fetch_items\", \"enrich\", \"rank\", \"top_k\"]\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"pipeline_group\": {\n"
            + "    \"main\": {\n"
            + "      \"pipeline\": [\"main_pipeline\"]\n"
            + "    }\n"
            + "  },\n"
            + "  \"flow_contract\": {\n"
            + "    \"common_input\": [],\n"
            + "    \"item_input\": [],\n"
            + "    \"common_output\": [],\n"
            + "    \"item_output\": [\"item_id\", \"display_score\", \"category\"]\n"
            + "  }\n"
            + "}";

    public static void main(String[] args) throws Exception {

        // =====================================================================
        // Step 1: Create the Engine
        // =====================================================================
        // Engine.create() parses the JSON config, validates the DAG, compiles
        // operators, and returns a thread-safe, reusable Engine instance.
        //
        // Options (all optional):
        //   Engine.withDebug(true)       — enable per-operator debug logging
        //   Engine.withLogPrefix("svc")  — prefix for log output
        //   Engine.withMetrics(provider) — plug in Prometheus/Micrometer metrics
        //   Engine.withResources(rp)     — supply external resources (Redis, HTTP, etc.)

        byte[] configBytes = PIPELINE_CONFIG.getBytes(StandardCharsets.UTF_8);

        Engine engine = Engine.create(configBytes,
                Engine.withDebug(true)  // enable debug for this demo
        );

        System.out.println("=== Engine created successfully ===");
        System.out.println();

        // =====================================================================
        // Step 2: Execute the pipeline
        // =====================================================================
        // The execute() method takes:
        //   - common: shared context fields (user profile, request params, etc.)
        //   - items:  initial item list (can be empty if recall operators produce items)
        //
        // Returns an Engine.Result containing:
        //   .common   — projected output common fields
        //   .items    — projected output items
        //   .warnings — non-fatal operator warnings
        //   .trace    — per-operator execution trace (timing, skip status)
        //   .error    — fatal error (null on success)

        Map<String, Object> common = new HashMap<>();
        common.put("user_id", "user_12345");
        common.put("request_ts", System.currentTimeMillis());

        // Items are empty — the recall_static operator will produce them
        List<Map<String, Object>> items = Collections.emptyList();

        Engine.Result result = engine.execute(common, items);

        // =====================================================================
        // Step 3: Inspect the result
        // =====================================================================

        if (result.error != null) {
            System.err.println("Pipeline failed: " + result.error.getMessage());
            return;
        }

        System.out.println("=== Pipeline Result ===");
        System.out.println();

        // Common output (projected by flow_contract.common_output)
        System.out.println("Common: " + result.common);
        System.out.println();

        // Items output (projected by flow_contract.item_output)
        System.out.println("Items (top 3 by score, descending):");
        for (int i = 0; i < result.items.size(); i++) {
            Map<String, Object> item = result.items.get(i);
            System.out.printf("  [%d] id=%-12s display_score=%-6s category=%s%n",
                    i + 1,
                    item.get("item_id"),
                    item.get("display_score"),
                    item.get("category"));
        }
        System.out.println();

        // Warnings (non-fatal issues from operators)
        if (result.warnings != null && !result.warnings.isEmpty()) {
            System.out.println("Warnings:");
            for (Engine.Warning w : result.warnings) {
                System.out.println("  - " + w.operator + ": " + w.err.getMessage());
            }
            System.out.println();
        }

        // Execution trace
        System.out.println("Trace:");
        for (OpTrace trace : result.trace) {
            String status = trace.skipped ? "SKIPPED" : "OK";
            System.out.printf("  %-20s %8.3f ms  [%s]%n",
                    trace.name,
                    trace.durationNs / 1_000_000.0,
                    status);
        }
        System.out.println();

        // =====================================================================
        // Step 4: Render the DAG
        // =====================================================================
        // renderDAG() produces a visualization of the execution graph.
        // Supported formats: "dot" (Graphviz) and "mermaid"
        // collapseLevel: 0 = full detail, 1+ = collapse SubFlows at that depth

        String dot = engine.renderDAG("dot", 0);
        System.out.println("=== DAG (Graphviz DOT) ===");
        System.out.println(dot);

        // Mermaid format (useful for GitHub/GitLab markdown rendering)
        String mermaid = engine.renderDAG("mermaid", 0);
        System.out.println("=== DAG (Mermaid) ===");
        System.out.println(mermaid);

        // =====================================================================
        // Step 5: PineServer (HTTP service mode)
        // =====================================================================
        // For production deployments, PineServer wraps the Engine in an HTTP
        // server with hot-reload, health checks, and observability endpoints.
        //
        // Endpoints:
        //   POST /execute  — run the pipeline (JSON body: {common, items})
        //   GET  /health   — liveness probe
        //   GET  /stats    — operator timing & scheduler statistics
        //   GET  /dag      — render DAG (?format=dot|mermaid&collapse=0)

        /*
        // --- Minimal PineServer setup ---

        // Point to a config file on disk (supports hot-reload on file change)
        PineServer server = new PineServer("/etc/pineapple/pipeline.json", 8080);

        // Optional: add middleware (auth, CORS, logging, etc.)
        server.addMiddleware(next -> exchange -> {
            exchange.getResponseHeaders().set("X-Powered-By", "Pineapple");
            next.handle(exchange);
        });

        // Start the server (blocks until shutdown)
        server.start();
        System.out.println("Pine server listening on :8080");

        // Graceful shutdown via shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(server::stop));
        */
    }
}
