"""Resource declaration types for Apple DSL.

Resources represent periodically-refreshed data (feature tables, configs, etc.)
that operators reference at runtime. They are declared in the pipeline Python
file and compiled into the unified JSON config alongside operators.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ResourceDecl:
    """Record of a resource declaration in a flow."""
    name: str
    resource_type: str
    interval: int
    params: dict[str, Any] = field(default_factory=dict)


class BaseResource:
    """Base class for generated resource types.

    Subclasses (generated by codegen) define _name, _default_interval, and
    _params_schema. Users instantiate them with typed params, then pass
    the instance to Flow.resource().
    """
    _name: str = ""
    _default_interval: int = 600
    _params_schema: dict[str, Any] = {}

    def __init__(self, *, interval: int | None = None, **params: Any):
        self.resource_type = self._name
        self.interval = interval if interval is not None else self._default_interval
        self.params = params
