package integration

import (
	"context"
	"testing"

	pine "github.com/Liam0205/pineapple/pine-go"
	_ "github.com/Liam0205/pineapple/pine-go/operators"
)

// TestAppleDSLe2e validates that a JSON config generated by the Apple DSL
// can be loaded and executed by the Pine engine.
func TestAppleDSLe2e(t *testing.T) {
	cfg := loadConfig(t, "../testdata/e2e_apple_dsl.json")
	engine, err := pine.NewEngine(cfg)
	if err != nil {
		t.Fatal(err)
	}

	// Young user: 20% discount
	req := &pine.Request{
		Common: map[string]any{"user_age": 15.0},
	}
	result, err := engine.Execute(context.Background(), req)
	if err != nil {
		t.Fatal(err)
	}

	// Items: a=100, b=200, c=50 with 20% discount → a=80, b=160, c=40
	// Sorted desc: b=160, a=80, c=40
	if len(result.Items) != 3 {
		t.Fatalf("expected 3 items, got %d: %v", len(result.Items), result.Items)
	}

	expectedPrices := []float64{160.0, 80.0, 40.0}
	for i, expected := range expectedPrices {
		got := result.Items[i]["item_final_price"]
		if got != expected {
			t.Errorf("item[%d] final_price: expected %v, got %v", i, expected, got)
		}
	}

	// Adult user: no discount
	req2 := &pine.Request{
		Common: map[string]any{"user_age": 30.0},
	}
	result2, err := engine.Execute(context.Background(), req2)
	if err != nil {
		t.Fatal(err)
	}

	// Sorted desc: b=200, a=100, c=50
	expectedPrices2 := []float64{200.0, 100.0, 50.0}
	for i, expected := range expectedPrices2 {
		got := result2.Items[i]["item_final_price"]
		if got != expected {
			t.Errorf("adult item[%d] final_price: expected %v, got %v", i, expected, got)
		}
	}
}
